name: Deploy React Application

on:
  push:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2

      - name: Install
        run: |
          npm install --force
          npm ci --ignore-scripts
          npm run build 
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
