name: Deploy React Application

on:
  push:
    tags:
      - "v*"
      
jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2

      - name: Install
        run: |
          npm config set legacy-peer-deps true
          npm i i18next i18next-http-backend i18next-browser-languagedetector react-i18next --save 
          npm install --force
          npm install gh-pages --save-dev
          npm ci --ignore-scripts
          git config --global user.email 7erminatrontzou7@gmail.com
          git config --global user.name ErminaTrontzou
          npm run build 
          npm run deploy
          

